version: 0.2

phases:
  install:
    commands:
      - echo "依存パッケージのインストール (必要な場合)"
      # - npm install (Node.jsツールを使う場合)
      
  build:
    commands:
      - echo "ビルド開始"
      # HTML/CSS/JSは通常ビルド不要ですが、最適化処理を追加可能
      # - npm run build (もしpackage.jsonにビルドスクリプトがある場合)
      
  post_build:
    commands:
      - echo "ビルド後の処理"
      # - aws s3 sync ./ s3://your-bucket-name --delete (直接S3へデプロイする場合)

artifacts:
  files:
    - '**/*'  # すべてのファイルをアーティファクトとして出力
  base-directory: .  # プロジェクトルートを基準に